[[redirects]]
  from = "http://ihassan.netlify.com/*"
  to = "http://hassanshabbir.net/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://ihassan.netlify.com/*"
  to = "https://hassanshabbir.net/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.hassanshabbir.net/*"
  to = "https://hassanshabbir.net/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.hassanshabbir.net/*"
  to = "https://hassanshabbir.net/:splat"
  status = 301
  force = true
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/javascript; charset=utf-8"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"
[[headers]]
  for = "*.jpg" # jpg files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/jpeg"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    Link = '''
    </profile.jpg>; rel=preload; as=image'''